# Generated by Django 6.0 on 2025-12-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
